# Generated by Django 4.1.7 on 2023-03-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelsmodel',
            name='label_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
