# Generated by Django 4.1.7 on 2023-03-08 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NotesApp', '0002_alter_labelsmodel_label_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isArchive', models.BooleanField(default=False)),
                ('isTrash', models.BooleanField(default=False)),
                ('colour', models.CharField(blank=True, max_length=10, null=True)),
                ('reminder', models.DateTimeField(blank=True, null=True)),
                ('collaborator', models.ManyToManyField(related_name='collaborater', to=settings.AUTH_USER_MODEL)),
                ('label', models.ManyToManyField(to='NotesApp.labelsmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
            },
        ),
    ]
