# Generated by Django 4.1.7 on 2023-03-13 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NotesApp', '0003_notesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmodel',
            name='collaborator',
            field=models.ManyToManyField(default=True, related_name='collaborater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notesmodel',
            name='label',
            field=models.ManyToManyField(default=True, to='NotesApp.labelsmodel'),
        ),
    ]
