# Generated by Django 4.1.7 on 2023-03-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0004_alter_notesmodel_collaborator_alter_notesmodel_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmodel',
            name='colour',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
